# See all available variables at https://megalinter.github.io/configuration/ and in linters documentation.

# General Config
APPLY_FIXES: all
DEFAULT_BRANCH: main
FILEIO_REPORTER: false
FILTER_REGEX_EXCLUDE: (\.github/workflows/|DSL/de\.unibonn\.simpleml/src/test/resources/)
IGNORE_GITIGNORED_FILES: true
PRINT_ALPACA: false
SHOW_ELAPSED_TIME: true
VALIDATE_ALL_CODEBASE: false

# JavaScript/TypeScript Config
JAVASCRIPT_DEFAULT_STYLE: prettier
JAVASCRIPT_PRETTIER_FILE_EXTENSIONS:
  - .js
  - .jsx
TYPESCRIPT_DEFAULT_STYLE: prettier
TYPESCRIPT_PRETTIER_FILE_EXTENSIONS:
  - .ts
  - .tsx

# Commands
PRE_COMMANDS:
  - command: npm install
    cwd: workspace

# Linters
ENABLE_LINTERS:
  - ACTION_ACTIONLINT # GitHub actions
  #  - ANSIBLE_ANSIBLE_LINT
  #  - ARM_ARM_TTK
  - BASH_EXEC
  - BASH_SHELLCHECK
  - BASH_SHFMT
  - C_CPPLINT
  #  - CLOJURE_CLJ_KONDO
  #  - CLOUDFORMATION_CFN_LINT
  #  - COFFEE_COFFEELINT
  #  - COPYPASTE_JSCPD # Slow + copy & paste sometimes makes sense, e.g. for tests
  - CPP_CPPLINT
  - CREDENTIALS_SECRETLINT
  - CSHARP_DOTNET_FORMAT
  - CSS_STYLELINT
  #  - CSS_SCSS_LINT
  #  - DART_DARTANALYZER
  - DOCKERFILE_DOCKERFILELINT
  - DOCKERFILE_HADOLINT
  #  - EDITORCONFIG_EDITORCONFIG_CHECKER # Overlaps with formatters for specific languages
  - ENV_DOTENV_LINTER
  #  - GHERKIN_GHERKIN_LINT
  - GIT_GIT_DIFF
  - GO_GOLANGCI_LINT
  - GO_REVIVE
  - GRAPHQL_GRAPHQL_SCHEMA_LINTER
  - GROOVY_NPM_GROOVY_LINT
  - HTML_HTMLHINT
  - JAVA_CHECKSTYLE
  - JAVASCRIPT_ES
  #  - JAVASCRIPT_STANDARD # We use prettier
  - JAVASCRIPT_PRETTIER
  - JSON_JSONLINT
  - JSON_ESLINT_PLUGIN_JSONC
  - JSON_V8R
  - JSON_PRETTIER
  - JSX_ESLINT
  - KOTLIN_KTLINT
  - KUBERNETES_KUBEVAL
  - LATEX_CHKTEX
  #  - LUA_LUACHECK
  - MARKDOWN_MARKDOWNLINT
  - MARKDOWN_REMARK_LINT
  - MARKDOWN_MARKDOWN_LINK_CHECK
  - MARKDOWN_MARKDOWN_TABLE_FORMATTER
  - OPENAPI_SPECTRAL
  #  - PERL_PERLCRITIC
  #  - PHP_BUILTIN
  #  - PHP_PHPCS
  #  - PHP_PHPSTAN
  #  - PHP_PSALM
  - POWERSHELL_POWERSHELL
  #  - PROTOBUF_PROTOLINT
  #  - PUPPET_PUPPET_LINT
  - PYTHON_PYLINT
  - PYTHON_BLACK
  - PYTHON_FLAKE8
  - PYTHON_ISORT
  - PYTHON_BANDIT
  - PYTHON_MYPY
  - R_LINTR
  #  - RAKU_RAKU
  - RST_RST_LINT
  - RST_RSTCHECK
  - RST_RSTFMT
  #  - RUBY_RUBOCOP
  - RUST_CLIPPY
  #  - SALESFORCE_SFDX_SCANNER_APEX
  #  - SALESFORCE_SFDX_SCANNER_AURA
  #  - SALESFORCE_SFDX_SCANNER_LWC
  #  - SCALA_SCALAFIX
  #  - SNAKEMAKE_LINT
  #  - SNAKEMAKE_SNAKEFMT
  #  - SPELL_MISSPELL # Many false positives
  #  - SPELL_CSPELL # Many false positives
  - SQL_SQL_LINT
  - SQL_SQLFLUFF
  - SQL_TSQLLINT
  #  - SWIFT_SWIFTLINT
  #  - TEKTON_TEKTON_LINT
  #  - TERRAFORM_TFLINT
  #  - TERRAFORM_TERRASCAN
  #  - TERRAFORM_TERRAGRUNT
  #  - TERRAFORM_TERRAFORM_FMT
  #  - TERRAFORM_CHECKOV
  - TSX_ESLINT
  - TYPESCRIPT_ES
  # - TYPESCRIPT_STANDARD # We use prettier
  - TYPESCRIPT_PRETTIER
  #  - VBDOTNET_DOTNET_FORMAT
  - XML_XMLLINT
  - YAML_PRETTIER
  - YAML_YAMLLINT
  - YAML_V8R
