# See all available variables at https://megalinter.github.io/configuration/ and in linters documentation.

# Config
APPLY_FIXES: all
DEFAULT_BRANCH: main
FILEIO_REPORTER: false
IGNORE_GITIGNORED_FILES: true
PRINT_ALPACA: false
SHOW_ELAPSED_TIME: true
FILTER_REGEX_EXCLUDE: (\.github/workflows/|DSL/de\.unibonn\.simpleml/src/test/resources)

JAVASCRIPT_DEFAULT_STYLE: prettier
JAVASCRIPT_PRETTIER_FILE_EXTENSIONS:
  - .js
  - .jsx
TYPESCRIPT_DEFAULT_STYLE: prettier
TYPESCRIPT_PRETTIER_FILE_EXTENSIONS:
  - .ts
  - .tsx

# Commands
PRE_COMMANDS:
  - command: npm install
    cwd: workspace

# Linters
ENABLE_LINTERS:
  - ACTION_ACTIONLINT
  - BASH_EXEC
  - BASH_SHELLCHECK
  - BASH_SHFMT
  - C_CPPLINT
  - CPP_CPPLINT
  - CREDENTIALS_SECRETLINT
  - CSHARP_DOTNET_FORMAT
  - CSS_STYLELINT
  - DOCKERFILE_DOCKERFILELINT
  - DOCKERFILE_HADOLINT
  - ENV_DOTENV_LINTER
  - GIT_GIT_DIFF
  - GO_GOLANGCI_LINT
  - GO_REVIVE
  - GRAPHQL_GRAPHQL_SCHEMA_LINTER
  - HTML_HTMLHINT
  - JAVA_CHECKSTYLE
  - JAVASCRIPT_ES
  - JAVASCRIPT_PRETTIER
  - JSON_JSONLINT
  - JSON_ESLINT_PLUGIN_JSONC
  - JSON_V8R
  - JSON_PRETTIER
  - JSX_ESLINT
  - KOTLIN_KTLINT
  - LATEX_CHKTEX
  - MARKDOWN_MARKDOWNLINT
  - MARKDOWN_REMARK_LINT
  - MARKDOWN_MARKDOWN_LINK_CHECK
  - MARKDOWN_MARKDOWN_TABLE_FORMATTER
  - OPENAPI_SPECTRAL
  - POWERSHELL_POWERSHELL
  - PYTHON_PYLINT
  - PYTHON_BLACK
  - PYTHON_FLAKE8
  - PYTHON_ISORT
  - PYTHON_BANDIT
  - PYTHON_MYPY
  - R_LINTR
  - RST_RST_LINT
  - RST_RSTCHECK
  - RST_RSTFMT
  - RUST_CLIPPY
  - SQL_SQL_LINT
  - SQL_SQLFLUFF
  - SQL_TSQLLINT
  - TSX_ESLINT
  - TYPESCRIPT_ES
  - TYPESCRIPT_PRETTIER
  - XML_XMLLINT
  - YAML_PRETTIER
  - YAML_YAMLLINT
  - YAML_V8R
