<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmi:version="2.0" name="simpleML" nsURI="http://www.unibonn.de/simpleml/SimpleML" nsPrefix="simpleML">
    <eClassifiers xsi:type="ecore:EClass" name="SmlAbstractObject" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="SmlAbstractAnnotatedObject" abstract="true" eSuperTypes="#//SmlAbstractObject">
        <eStructuralFeatures xsi:type="ecore:EReference" name="annotationCalls" upperBound="-1" eType="#//SmlAnnotationCall" containment="true" />
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SmlAbstractDeclaration" abstract="true" eSuperTypes="#//SmlAbstractAnnotatedObject">
        <eStructuralFeatures xsi:type="ecore:EReference" name="annotationCallList" eType="#//SmlAnnotationCallList" containment="true" />
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" />
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SmlAbstractCall" abstract="true" eSuperTypes="#//SmlAbstractObject">
        <eStructuralFeatures xsi:type="ecore:EReference" name="argumentList" eType="#//SmlArgumentList" containment="true" />
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SmlAbstractCallable" abstract="true" eSuperTypes="#//SmlAbstractObject">
        <eStructuralFeatures xsi:type="ecore:EReference" name="parameterList" eType="#//SmlParameterList" containment="true" />
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SmlAbstractClassMember" abstract="true" eSuperTypes="#//SmlAbstractDeclaration" />
    <eClassifiers xsi:type="ecore:EClass" name="SmlAbstractCompilationUnitMember" abstract="true" eSuperTypes="#//SmlAbstractDeclaration" />
    <eClassifiers xsi:type="ecore:EClass" name="SmlAbstractLocalVariable" abstract="true" eSuperTypes="#//SmlAbstractDeclaration" />
    <eClassifiers xsi:type="ecore:EClass" name="SmlAbstractNamedTypeDeclaration" abstract="true" eSuperTypes="#//SmlAbstractDeclaration" />
    <eClassifiers xsi:type="ecore:EClass" name="SmlAbstractProtocolToken" abstract="true" eSuperTypes="#//SmlAbstractDeclaration" />
    <eClassifiers xsi:type="ecore:EClass" name="SmlAbstractResult" abstract="true" eSuperTypes="#//SmlAbstractDeclaration" />
    <eClassifiers xsi:type="ecore:EClass" name="SmlAnnotation" eSuperTypes="#//SmlAbstractCallable #//SmlAbstractCompilationUnitMember">
        <eStructuralFeatures xsi:type="ecore:EReference" name="constraintList" eType="#//SmlConstraintList" containment="true" />
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SmlAnnotationCallList" eSuperTypes="#//SmlAbstractAnnotatedObject" />
    <eClassifiers xsi:type="ecore:EClass" name="SmlAnnotationCall" eSuperTypes="#//SmlAbstractCall">
        <eStructuralFeatures xsi:type="ecore:EReference" name="annotation" eType="#//SmlAnnotation" />
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SmlAttribute" eSuperTypes="#//SmlAbstractClassMember #//SmlAbstractProtocolToken">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="static" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" />
        <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//SmlAbstractType" containment="true" />
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SmlClass" abstract="false" eSuperTypes="#//SmlAbstractCallable #//SmlAbstractClassMember #//SmlAbstractCompilationUnitMember #//SmlAbstractNamedTypeDeclaration">
        <eStructuralFeatures xsi:type="ecore:EReference" name="typeParameterList" eType="#//SmlTypeParameterList" containment="true" />
        <eStructuralFeatures xsi:type="ecore:EReference" name="parentTypeList" eType="#//SmlParentTypeList" containment="true" />
        <eStructuralFeatures xsi:type="ecore:EReference" name="constraintList" eType="#//SmlConstraintList" containment="true" />
        <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="#//SmlClassBody" containment="true" />
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SmlClassBody" eSuperTypes="#//SmlAbstractObject">
        <eStructuralFeatures xsi:type="ecore:EReference" name="members" upperBound="-1" eType="#//SmlAbstractObject" containment="true" />
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SmlProtocol" eSuperTypes="#//SmlAbstractObject">
        <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="#//SmlProtocolBody" containment="true" />
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SmlProtocolBody" eSuperTypes="#//SmlAbstractObject">
        <eStructuralFeatures xsi:type="ecore:EReference" name="subtermList" eType="#//SmlProtocolSubtermList" containment="true" />
        <eStructuralFeatures xsi:type="ecore:EReference" name="term" eType="#//SmlAbstractProtocolTerm" containment="true" />
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SmlProtocolSubtermList" eSuperTypes="#//SmlAbstractObject">
        <eStructuralFeatures xsi:type="ecore:EReference" name="subterms" upperBound="-1" eType="#//SmlProtocolSubterm" containment="true" />
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SmlProtocolSubterm" eSuperTypes="#//SmlAbstractProtocolToken">
        <eStructuralFeatures xsi:type="ecore:EReference" name="term" eType="#//SmlAbstractProtocolTerm" containment="true" />
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SmlAbstractProtocolTerm" abstract="true" eSuperTypes="#//SmlAbstractObject" />
    <eClassifiers xsi:type="ecore:EClass" name="SmlProtocolAlternative" eSuperTypes="#//SmlAbstractProtocolTerm">
        <eStructuralFeatures xsi:type="ecore:EReference" name="terms" upperBound="-1" eType="#//SmlAbstractProtocolTerm" containment="true" />
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SmlProtocolSequence" eSuperTypes="#//SmlAbstractProtocolTerm">
        <eStructuralFeatures xsi:type="ecore:EReference" name="terms" upperBound="-1" eType="#//SmlAbstractProtocolTerm" containment="true" />
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SmlProtocolQuantifiedTerm" eSuperTypes="#//SmlAbstractProtocolTerm">
        <eStructuralFeatures xsi:type="ecore:EReference" name="term" eType="#//SmlAbstractProtocolTerm" containment="true" />
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="quantifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" />
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SmlProtocolComplement" eSuperTypes="#//SmlAbstractProtocolTerm">
        <eStructuralFeatures xsi:type="ecore:EReference" name="universe" eType="#//SmlProtocolTokenClass" containment="true" />
        <eStructuralFeatures xsi:type="ecore:EReference" name="referenceList" eType="#//SmlProtocolReferenceList" containment="true" />
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SmlProtocolReferenceList" eSuperTypes="#//SmlAbstractProtocolTerm">
        <eStructuralFeatures xsi:type="ecore:EReference" name="references" upperBound="-1" eType="#//SmlProtocolReference" containment="true" />
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SmlProtocolReference" eSuperTypes="#//SmlAbstractProtocolTerm">
        <eStructuralFeatures xsi:type="ecore:EReference" name="token" eType="#//SmlAbstractProtocolToken" />
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SmlProtocolTokenClass" eSuperTypes="#//SmlAbstractProtocolTerm">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" />
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SmlProtocolParenthesizedTerm" eSuperTypes="#//SmlAbstractProtocolTerm">
        <eStructuralFeatures xsi:type="ecore:EReference" name="term" eType="#//SmlAbstractProtocolTerm" containment="true" />
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SmlCompilationUnit" eSuperTypes="#//SmlAbstractDeclaration">
        <eStructuralFeatures xsi:type="ecore:EReference" name="imports" upperBound="-1" eType="#//SmlImport" containment="true" />
        <eStructuralFeatures xsi:type="ecore:EReference" name="members" upperBound="-1" eType="#//SmlAbstractAnnotatedObject" containment="true" />
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SmlImport" eSuperTypes="#//SmlAbstractObject">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="importedNamespace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" />
        <eStructuralFeatures xsi:type="ecore:EReference" name="alias" eType="#//SmlImportAlias" containment="true" />
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SmlImportAlias" eSuperTypes="#//SmlAbstractObject">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" />
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SmlEnum" eSuperTypes="#//SmlAbstractNamedTypeDeclaration #//SmlAbstractClassMember #//SmlAbstractCompilationUnitMember">
        <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="#//SmlEnumBody" containment="true" />
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SmlEnumBody" eSuperTypes="#//SmlAbstractObject">
        <eStructuralFeatures xsi:type="ecore:EReference" name="variants" upperBound="-1" eType="#//SmlEnumVariant" containment="true" />
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SmlEnumVariant" eSuperTypes="#//SmlAbstractCallable #//SmlAbstractNamedTypeDeclaration">
        <eStructuralFeatures xsi:type="ecore:EReference" name="typeParameterList" eType="#//SmlTypeParameterList" containment="true" />
        <eStructuralFeatures xsi:type="ecore:EReference" name="constraintList" eType="#//SmlConstraintList" containment="true" />
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SmlFunction" eSuperTypes="#//SmlAbstractCallable #//SmlAbstractClassMember #//SmlAbstractCompilationUnitMember #//SmlAbstractProtocolToken">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="static" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" />
        <eStructuralFeatures xsi:type="ecore:EReference" name="typeParameterList" eType="#//SmlTypeParameterList" containment="true" />
        <eStructuralFeatures xsi:type="ecore:EReference" name="resultList" eType="#//SmlResultList" containment="true" />
        <eStructuralFeatures xsi:type="ecore:EReference" name="constraintList" eType="#//SmlConstraintList" containment="true" />
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SmlParameterList" eSuperTypes="#//SmlAbstractObject">
        <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1" eType="#//SmlParameter" containment="true" />
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SmlLambdaParameterList" eSuperTypes="#//SmlAbstractExpression #//SmlParameterList" />
    <eClassifiers xsi:type="ecore:EClass" name="SmlParameter" eSuperTypes="#//SmlAbstractLocalVariable">
        <eStructuralFeatures xsi:type="ecore:EReference" name="defaultValue" eType="#//SmlAbstractExpression" containment="true" />
        <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//SmlAbstractType" containment="true" />
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="variadic" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" />
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SmlResultList" eSuperTypes="#//SmlAbstractObject">
        <eStructuralFeatures xsi:type="ecore:EReference" name="results" upperBound="-1" eType="#//SmlResult" containment="true" />
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SmlResult" eSuperTypes="#//SmlAbstractResult">
        <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//SmlAbstractType" containment="true" />
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SmlStep" eSuperTypes="#//SmlAbstractCallable #//SmlAbstractCompilationUnitMember">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" />
        <eStructuralFeatures xsi:type="ecore:EReference" name="resultList" eType="#//SmlResultList" containment="true" />
        <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="#//SmlBlock" containment="true" />
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SmlWorkflow" eSuperTypes="#//SmlAbstractCompilationUnitMember">
        <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="#//SmlBlock" containment="true" />
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SmlBlock" eSuperTypes="#//SmlAbstractObject">
        <eStructuralFeatures xsi:type="ecore:EReference" name="statements" upperBound="-1" eType="#//SmlAbstractStatement" containment="true" />
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SmlAbstractStatement" abstract="true" eSuperTypes="#//SmlAbstractObject" />
    <eClassifiers xsi:type="ecore:EClass" name="SmlAssignment" eSuperTypes="#//SmlAbstractStatement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="assigneeList" eType="#//SmlAssigneeList" containment="true" />
        <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//SmlAbstractExpression" containment="true" />
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SmlAssigneeList" eSuperTypes="#//SmlAbstractObject">
        <eStructuralFeatures xsi:type="ecore:EReference" name="assignees" upperBound="-1" eType="#//SmlAbstractAssignee" containment="true" />
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SmlAbstractAssignee" abstract="true" eSuperTypes="#//SmlAbstractObject" />
    <eClassifiers xsi:type="ecore:EClass" name="SmlPlaceholder" eSuperTypes="#//SmlAbstractAssignee #//SmlAbstractLocalVariable" />
    <eClassifiers xsi:type="ecore:EClass" name="SmlWildcard" eSuperTypes="#//SmlAbstractAssignee" />
    <eClassifiers xsi:type="ecore:EClass" name="SmlYield" eSuperTypes="#//SmlAbstractAssignee">
        <eStructuralFeatures xsi:type="ecore:EReference" name="result" eType="#//SmlResult" />
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SmlBlockLambdaResult" eSuperTypes="#//SmlAbstractAssignee #//SmlAbstractResult" />
    <eClassifiers xsi:type="ecore:EClass" name="SmlExpressionStatement" eSuperTypes="#//SmlAbstractStatement">
        <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//SmlAbstractExpression" containment="true" />
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SmlAbstractExpression" abstract="true" eSuperTypes="#//SmlAbstractObject" />
    <eClassifiers xsi:type="ecore:EClass" name="SmlAbstractLiteral" abstract="true" eSuperTypes="#//SmlAbstractExpression" />
    <eClassifiers xsi:type="ecore:EClass" name="SmlBoolean" eSuperTypes="#//SmlAbstractLiteral">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="true" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" />
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SmlAbstractNumber" abstract="true" eSuperTypes="#//SmlAbstractLiteral" />
    <eClassifiers xsi:type="ecore:EClass" name="SmlFloat" eSuperTypes="#//SmlAbstractNumber">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" />
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SmlInt" eSuperTypes="#//SmlAbstractNumber">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" />
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SmlString" eSuperTypes="#//SmlAbstractLiteral">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" />
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SmlTemplateString" eSuperTypes="#//SmlAbstractExpression">
        <eStructuralFeatures xsi:type="ecore:EReference" name="expressions" upperBound="-1" eType="#//SmlAbstractExpression" containment="true" />
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SmlAbstractTemplateStringPart" abstract="true" eSuperTypes="#//SmlAbstractLiteral">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" />
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SmlTemplateStringStart" eSuperTypes="#//SmlAbstractTemplateStringPart" />
    <eClassifiers xsi:type="ecore:EClass" name="SmlTemplateStringInner" eSuperTypes="#//SmlAbstractTemplateStringPart" />
    <eClassifiers xsi:type="ecore:EClass" name="SmlTemplateStringEnd" eSuperTypes="#//SmlAbstractTemplateStringPart" />
    <eClassifiers xsi:type="ecore:EClass" name="SmlAbstractLambda" abstract="true" eSuperTypes="#//SmlAbstractCallable #//SmlAbstractExpression" />
    <eClassifiers xsi:type="ecore:EClass" name="SmlBlockLambda" eSuperTypes="#//SmlAbstractLambda">
        <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="#//SmlBlock" containment="true" />
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SmlExpressionLambda" eSuperTypes="#//SmlAbstractLambda">
        <eStructuralFeatures xsi:type="ecore:EReference" name="result" eType="#//SmlAbstractExpression" containment="true" />
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SmlInfixOperation" eSuperTypes="#//SmlAbstractExpression">
        <eStructuralFeatures xsi:type="ecore:EReference" name="leftOperand" eType="#//SmlAbstractExpression" containment="true" />
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" />
        <eStructuralFeatures xsi:type="ecore:EReference" name="rightOperand" eType="#//SmlAbstractExpression" containment="true" />
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SmlNull" eSuperTypes="#//SmlAbstractLiteral" />
    <eClassifiers xsi:type="ecore:EClass" name="SmlPrefixOperation" eSuperTypes="#//SmlAbstractExpression">
        <eStructuralFeatures xsi:type="ecore:EReference" name="operand" eType="#//SmlAbstractExpression" containment="true" />
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" />
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SmlReference" eSuperTypes="#//SmlAbstractExpression">
        <eStructuralFeatures xsi:type="ecore:EReference" name="declaration" eType="#//SmlAbstractDeclaration" />
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SmlParenthesizedExpression" eSuperTypes="#//SmlAbstractExpression">
        <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//SmlAbstractExpression" containment="true" />
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SmlAbstractChainedExpression" abstract="true" eSuperTypes="#//SmlAbstractExpression">
        <eStructuralFeatures xsi:type="ecore:EReference" name="receiver" eType="#//SmlAbstractExpression" containment="true" />
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SmlCall" eSuperTypes="#//SmlAbstractCall #//SmlAbstractChainedExpression">
        <eStructuralFeatures xsi:type="ecore:EReference" name="typeArgumentList" eType="#//SmlTypeArgumentList" containment="true" />
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SmlArgumentList" eSuperTypes="#//SmlAbstractObject">
        <eStructuralFeatures xsi:type="ecore:EReference" name="arguments" upperBound="-1" eType="#//SmlArgument" containment="true" />
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SmlArgument" eSuperTypes="#//SmlAbstractExpression">
        <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" eType="#//SmlParameter" />
        <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//SmlAbstractExpression" containment="true" />
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SmlIndexedAccess" eSuperTypes="#//SmlAbstractChainedExpression">
        <eStructuralFeatures xsi:type="ecore:EReference" name="index" eType="#//SmlAbstractExpression" containment="true" />
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SmlMemberAccess" eSuperTypes="#//SmlAbstractChainedExpression">
        <eStructuralFeatures xsi:type="ecore:EReference" name="member" eType="#//SmlReference" containment="true" />
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="nullSafe" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" />
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SmlAbstractType" abstract="true" eSuperTypes="#//SmlAbstractObject" />
    <eClassifiers xsi:type="ecore:EClass" name="SmlCallableType" eSuperTypes="#//SmlAbstractCallable #//SmlAbstractType">
        <eStructuralFeatures xsi:type="ecore:EReference" name="resultList" eType="#//SmlResultList" containment="true" />
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SmlMemberType" eSuperTypes="#//SmlAbstractType">
        <eStructuralFeatures xsi:type="ecore:EReference" name="member" eType="#//SmlNamedType" containment="true" />
        <eStructuralFeatures xsi:type="ecore:EReference" name="receiver" eType="#//SmlAbstractType" containment="true" />
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SmlNamedType" eSuperTypes="#//SmlAbstractType">
        <eStructuralFeatures xsi:type="ecore:EReference" name="declaration" eType="#//SmlAbstractNamedTypeDeclaration" />
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="nullable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" />
        <eStructuralFeatures xsi:type="ecore:EReference" name="typeArgumentList" eType="#//SmlTypeArgumentList" containment="true" />
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SmlParenthesizedType" eSuperTypes="#//SmlAbstractType">
        <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//SmlAbstractType" containment="true" />
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SmlUnionType" eSuperTypes="#//SmlAbstractType">
        <eStructuralFeatures xsi:type="ecore:EReference" name="typeArgumentList" eType="#//SmlTypeArgumentList" containment="true" />
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SmlParentTypeList" eSuperTypes="#//SmlAbstractObject">
        <eStructuralFeatures xsi:type="ecore:EReference" name="parentTypes" upperBound="-1" eType="#//SmlAbstractType" containment="true" />
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SmlTypeParameterList" eSuperTypes="#//SmlAbstractObject">
        <eStructuralFeatures xsi:type="ecore:EReference" name="typeParameters" upperBound="-1" eType="#//SmlTypeParameter" containment="true" />
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SmlTypeParameter" eSuperTypes="#//SmlAbstractNamedTypeDeclaration">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="variance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" />
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" />
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SmlTypeArgumentList" eSuperTypes="#//SmlAbstractObject">
        <eStructuralFeatures xsi:type="ecore:EReference" name="typeArguments" upperBound="-1" eType="#//SmlTypeArgument" containment="true" />
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SmlTypeArgument" eSuperTypes="#//SmlAbstractObject">
        <eStructuralFeatures xsi:type="ecore:EReference" name="typeParameter" eType="#//SmlTypeParameter" />
        <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//SmlAbstractTypeArgumentValue" containment="true" />
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SmlAbstractTypeArgumentValue" abstract="true" eSuperTypes="#//SmlAbstractObject" />
    <eClassifiers xsi:type="ecore:EClass" name="SmlStarProjection" eSuperTypes="#//SmlAbstractTypeArgumentValue" />
    <eClassifiers xsi:type="ecore:EClass" name="SmlTypeProjection" eSuperTypes="#//SmlAbstractTypeArgumentValue">
        <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//SmlAbstractType" containment="true" />
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="variance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" />
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SmlConstraintList" eSuperTypes="#//SmlAbstractObject">
        <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" upperBound="-1" eType="#//SmlAbstractConstraint" containment="true" />
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SmlAbstractConstraint" abstract="true" eSuperTypes="#//SmlAbstractObject"/>
    <eClassifiers xsi:type="ecore:EClass" name="SmlTypeParameterConstraint" eSuperTypes="#//SmlAbstractConstraint">
        <eStructuralFeatures xsi:type="ecore:EReference" name="leftOperand" eType="#//SmlTypeParameter" />
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" />
        <eStructuralFeatures xsi:type="ecore:EReference" name="rightOperand" eType="#//SmlAbstractType" containment="true" />
    </eClassifiers>
</ecore:EPackage>
