name: Main
on:
  push:
    branches: [ main ]

jobs:
  # Build and test DSL component
  build-dsl:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./DSL
    strategy:
      matrix:
        java-version: [ 17 ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: ${{ matrix.java-version }}
          cache: gradle

      # See https://docs.github.com/en/actions/guides/building-and-testing-java-with-gradle
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Test with Gradle
        run: ./gradlew check koverMergedXmlReport

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: DSL/build/reports/kover/merged/xml
          files: report.xml

  # Build and test Runner component
  build-runner:
    strategy:
      matrix:
        python-version: [ "3.10" ]
    uses: lars-reimann/.github/.github/workflows/poetry-codecov-reusable.yml@main
    with:
      working-directory: Runner
      python-version: ${{ matrix.python-version }}
      module-name: safeds_runner
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
