name: Main
on:
  push:
    branches: [ main ]

jobs:
  build-dsl:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Generate Langium files
        run: npm run langium:generate

      - name: Compile TypeScript
        run: npm run build

      - name: Test with Vitest
        run: npm run test-with-coverage

      - name: Upload coverage to Codecov
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: coverage
          files: coverage-final.json
