name: Pull Request

on:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.head_ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  # Build and test DSL component
  build-dsl:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./DSL
    strategy:
      matrix:
        java-version: [17]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: ${{ matrix.java-version }}
          cache: gradle

      # See https://docs.github.com/en/actions/guides/building-and-testing-java-with-gradle
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Test with Gradle
        run: ./gradlew build koverMergedXmlReport

      - name: Upload test report
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: Test report
          # upload-artifact does not use working-directory
          path: |
            DSL/com.larsreimann.safeds/build/reports/tests/test/
            DSL/com.larsreimann.safeds.ide/build/reports/tests/test/

      - name: Upload coverage to Codecov
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: DSL/build/reports/kover/merged/xml
          files: report.xml

  # Build and test Runner component
  build-runner:
    strategy:
      matrix:
        python-version:
          - '3.10'
          - '3.11'
    uses: lars-reimann/.github/.github/workflows/poetry-codecov-reusable.yml@main
    with:
      working-directory: Runner
      python-version: ${{ matrix.python-version }}
      module-name: safeds_runner
      coverage: ${{ matrix.python-version == '3.10' }}
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
