name: Pull Request

on:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.head_ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  # Build and test DSL component
  build-dsl:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./DSL

    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: DSL/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Generate Langium files
        run: npm run langium:generate

      - name: Compile TypeScript
        run: npm run build

      - name: Test with Vitest
        run: npm run test-with-coverage

      - name: Upload coverage to Codecov
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: DSL/coverage
          files: clover.xml

  # Build and test Runner component
  build-runner:
    strategy:
      matrix:
        python-version:
          - '3.10'
          - '3.11'
    uses: lars-reimann/.github/.github/workflows/poetry-codecov-reusable.yml@main
    with:
      working-directory: Runner
      python-version: ${{ matrix.python-version }}
      module-name: safeds_runner
      coverage: ${{ matrix.python-version == '3.10' }}
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
